[package]
name = "no-free-lunch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.12.0", features = ["full"]}
chrono = "0.4.19"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity.git"
branch = "current"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"]
